# --- PLAY 1 ---
- name: Copy specific files to a remote destination
  hosts: all
  become: true
  tasks:
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: /home/ubuntu/flaskops
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy app.py and requirements.txt
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0600'
      loop:
        - { src: '../app/app.py', dest: '/home/ubuntu/flaskops' }
        - { src: '../app/requirements.txt', dest: '/home/ubuntu/flaskops' }

# --- PLAY 2 ---
- name: Install Python 3, pip and dependencies
  hosts: all
  become: true
  tasks:
    - name: Install Python 3
      ansible.builtin.package:
        name: python3
        state: present

    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: "/home/ubuntu/flaskops/requirements.txt"

# --- PLAY 3 ---
- name: Configure systemd service
  hosts: all
  become: true
  tasks:
    - name: Deploy systemd file
      ansible.builtin.template:
        src: flaskapp.service.j2
        dest: /etc/systemd/system/flaskapp.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart flaskapp

  handlers:
    - name: Restart flaskapp
      ansible.builtin.systemd:
        name: flaskapp
        state: restarted

# --- PLAY 4 ---
- name: Start and enable flaskapp service
  hosts: all
  become: true
  tasks:
    - name: Ensure flaskapp is running
      ansible.builtin.systemd:
        name: flaskapp
        state: started
        enabled: true
        daemon_reload: true
