name: FlaskOps Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION : "ap-south-1"

permissions:
  id-token: write
  contents: read

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

  configure_AWS:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::703623468959:role/GitHubOIDC_FlaskOps
        role-session-name: sample-role
        aws-region: ${{ env.AWS_REGION }}

  terraform_deploy:
    needs: configure_AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::703623468959:role/GitHubOIDC_FlaskOps
        role-session-name: sample-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.14.1"

    - name: Print Terraform version
      run: terraform --version
    
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Unlock state file  
      run: terraform force-unlock -force 5d64f780-a75f-5ba7-13e1-bee474901783
      working-directory: ./terraform
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Approve
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Output Public IP address
      outputs:
        output1: ${{ steps.get_ip.outputs.public_ip_address }} 
      steps:
        id: get_ip
        run: echo "public_ip_address=$(terraform output public_ip_address)" >> $GITHUB_OUTPUT
 
 
  retrieve_ec2_public_ip:
    name: Retrieve EC2 Public IP address
    needs: terraform_deploy
    runs-on: ubuntu-latest
    steps:
      -env:
        OUTPUT1: ${{needs.terraform_deploy.outputs.output1}}
       run: echo "$OUTPUT1"
       


